/*	SCCS Id: @(#)rndvault.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#ifndef RNDVAULT_H
#define RNDVAULT_H

struct rndvault {
	schar rarity;
	schar minlev;
	schar maxlev;
} rndvaults[] = {
	{ 10, 2, 15 },
	{ 10, 3, 8 },
	{ 10, 20, 25 },
	{ 10, 18, 25 },
	{ 10, 10, 20 },
};
#define NUM_VAULTS 5

#endif /* RNDVAULT_H */
